version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - docker-net
    volumes:
      - ${POSTGRES_HOME_DIR}/data:/var/lib/pg_data
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
      PG_DATA: /var/lib/pg_data
    healthcheck:
      test:
        [
          "CMD-SHELL", "pg_isready"
        ]
      timeout: 50s
      retries: 10

networks:
  docker-net:
